name: MHCosmeticsDisabler
version: '${project.version}'
main: me.hapily.plugins.mhcosmeticsdisabler.MHCosmeticsDisabler
api-version: 1.16
authors: [ hapily ]
description: Disables the 'MinehutCosmetics' plugin.
